"""init

Revision ID: 3be6bcb59646
Revises: 
Create Date: 2026-09-10 17:29:42.227534
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '3be6bcb59646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_graph_version_id', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_graph_version_id'], ['graph_versions.id'], name='fk_projects_default_graph_version_id', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('graph_node_id', sa.String(length=100), nullable=True),
    sa.Column('demand_units', sa.Integer(), nullable=False),
    sa.Column('service_seconds', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.String(length=20), nullable=True),
    sa.Column('window_end', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_ref', name='uq_customers_project_external_ref')
    )
    op.create_index(op.f('ix_customers_project_id'), 'customers', ['project_id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('depots',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('graph_node_id', sa.String(length=100), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_project_id'), 'depots', ['project_id'], unique=False)
    op.create_table('graph_versions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_versions_project_id'), 'graph_versions', ['project_id'], unique=False)
    op.create_table('traffic_scenarios',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_scenarios_project_id'), 'traffic_scenarios', ['project_id'], unique=False)
    op.create_table('benchmark_experiments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('traffic_scenario_id', sa.UUID(), nullable=True),
    sa.Column('algorithms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traffic_scenario_id'], ['traffic_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_experiments_project_id'), 'benchmark_experiments', ['project_id'], unique=False)
    op.create_table('optimization_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('traffic_scenario_id', sa.UUID(), nullable=True),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('algorithm_version', sa.String(length=30), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('objective_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('best_cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traffic_scenario_id'], ['traffic_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_jobs_idempotency_key'), 'optimization_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_optimization_jobs_project_id'), 'optimization_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_optimization_jobs_status'), 'optimization_jobs', ['status'], unique=False)
    op.create_table('traffic_edges',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('graph_edge_id', sa.String(length=100), nullable=False),
    sa.Column('time_bucket', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('congestion_factor', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['traffic_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'graph_edge_id', 'time_bucket', name='uq_traffic_edges_scenario_edge_bucket')
    )
    op.create_index(op.f('ix_traffic_edges_graph_edge_id'), 'traffic_edges', ['graph_edge_id'], unique=False)
    op.create_index(op.f('ix_traffic_edges_scenario_id'), 'traffic_edges', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_traffic_edges_time_bucket'), 'traffic_edges', ['time_bucket'], unique=False)
    op.create_table('vehicles',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_km', sa.Float(), nullable=False),
    sa.Column('max_route_seconds', sa.Integer(), nullable=False),
    sa.Column('start_depot_id', sa.UUID(), nullable=False),
    sa.Column('end_depot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['end_depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_vehicles_project_code')
    )
    op.create_index(op.f('ix_vehicles_project_id'), 'vehicles', ['project_id'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('repetition_no', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('objective_cost', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('travel_time_s', sa.Float(), nullable=False),
    sa.Column('congestion_cost', sa.Float(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['benchmark_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_algorithm'), 'benchmark_runs', ['algorithm'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_experiment_id'), 'benchmark_runs', ['experiment_id'], unique=False)
    op.create_table('optimization_iterations',
    sa.Column('optimization_job_id', sa.UUID(), nullable=False),
    sa.Column('iteration_no', sa.Integer(), nullable=False),
    sa.Column('best_cost', sa.Float(), nullable=False),
    sa.Column('mean_cost', sa.Float(), nullable=False),
    sa.Column('diversity', sa.Float(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_job_id'], ['optimization_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_iterations_iteration_no'), 'optimization_iterations', ['iteration_no'], unique=False)
    op.create_index(op.f('ix_optimization_iterations_optimization_job_id'), 'optimization_iterations', ['optimization_job_id'], unique=False)
    op.create_table('route_plans',
    sa.Column('optimization_job_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('total_time_s', sa.Float(), nullable=False),
    sa.Column('congestion_cost', sa.Float(), nullable=False),
    sa.Column('objective_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_job_id'], ['optimization_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_plans_optimization_job_id'), 'route_plans', ['optimization_job_id'], unique=False)
    op.create_index(op.f('ix_route_plans_project_id'), 'route_plans', ['project_id'], unique=False)
    op.create_table('vehicle_routes',
    sa.Column('route_plan_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('time_s', sa.Float(), nullable=False),
    sa.Column('load_units', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_routes_geometry', 'vehicle_routes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_vehicle_routes_route_plan_id'), 'vehicle_routes', ['route_plan_id'], unique=False)
    op.create_index(op.f('ix_vehicle_routes_sequence_no'), 'vehicle_routes', ['sequence_no'], unique=False)
    op.create_table('route_stops',
    sa.Column('vehicle_route_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('depot_id', sa.UUID(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.String(length=20), nullable=False),
    sa.Column('eta_seconds', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_route_id'], ['vehicle_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_sequence_no'), 'route_stops', ['sequence_no'], unique=False)
    op.create_index(op.f('ix_route_stops_vehicle_route_id'), 'route_stops', ['vehicle_route_id'], unique=False)
    op.create_table('route_legs',
    sa.Column('vehicle_route_id', sa.UUID(), nullable=False),
    sa.Column('from_stop_id', sa.UUID(), nullable=False),
    sa.Column('to_stop_id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('travel_time_s', sa.Float(), nullable=False),
    sa.Column('congestion_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['to_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['vehicle_route_id'], ['vehicle_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_legs_geometry', 'route_legs', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_route_legs_vehicle_route_id'), 'route_legs', ['vehicle_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_legs_vehicle_route_id'), table_name='route_legs')
    op.drop_index('idx_route_legs_geometry', table_name='route_legs', postgresql_using='gist')
    op.drop_table('route_legs')
    op.drop_index(op.f('ix_route_stops_vehicle_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_sequence_no'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_vehicle_routes_sequence_no'), table_name='vehicle_routes')
    op.drop_index(op.f('ix_vehicle_routes_route_plan_id'), table_name='vehicle_routes')
    op.drop_index('idx_vehicle_routes_geometry', table_name='vehicle_routes', postgresql_using='gist')
    op.drop_table('vehicle_routes')
    op.drop_index(op.f('ix_route_plans_project_id'), table_name='route_plans')
    op.drop_index(op.f('ix_route_plans_optimization_job_id'), table_name='route_plans')
    op.drop_table('route_plans')
    op.drop_index(op.f('ix_optimization_iterations_optimization_job_id'), table_name='optimization_iterations')
    op.drop_index(op.f('ix_optimization_iterations_iteration_no'), table_name='optimization_iterations')
    op.drop_table('optimization_iterations')
    op.drop_index(op.f('ix_benchmark_runs_experiment_id'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_algorithm'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_project_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_traffic_edges_time_bucket'), table_name='traffic_edges')
    op.drop_index(op.f('ix_traffic_edges_scenario_id'), table_name='traffic_edges')
    op.drop_index(op.f('ix_traffic_edges_graph_edge_id'), table_name='traffic_edges')
    op.drop_table('traffic_edges')
    op.drop_index(op.f('ix_optimization_jobs_status'), table_name='optimization_jobs')
    op.drop_index(op.f('ix_optimization_jobs_project_id'), table_name='optimization_jobs')
    op.drop_index(op.f('ix_optimization_jobs_idempotency_key'), table_name='optimization_jobs')
    op.drop_table('optimization_jobs')
    op.drop_index(op.f('ix_benchmark_experiments_project_id'), table_name='benchmark_experiments')
    op.drop_table('benchmark_experiments')
    op.drop_index(op.f('ix_traffic_scenarios_project_id'), table_name='traffic_scenarios')
    op.drop_table('traffic_scenarios')
    op.drop_index(op.f('ix_graph_versions_project_id'), table_name='graph_versions')
    op.drop_table('graph_versions')
    op.drop_index(op.f('ix_depots_project_id'), table_name='depots')
    op.drop_table('depots')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_project_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
